Repository vaadin/portlet, pull requests merged in 2023-08, with the labels that each got.

#249 test: fix flaky tests
  vaadin-portlet-integration-tests/shared/src/main/java/com/vaadin/flow/portal/AbstractPlutoPortalTest.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/lifecycle/EventHandlerIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/MinimizedStateRenderIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/RenderIT.java
Labels: target/1.0, target/2.0

#250 test: fix flaky tests (#249) (CP: 2.0)
  vaadin-portlet-integration-tests/shared/src/main/java/com/vaadin/flow/portal/AbstractPlutoPortalTest.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/lifecycle/EventHandlerIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/MinimizedStateRenderIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/RenderIT.java
Labels: cherry pick

#251 test: fix flaky tests (#249) (CP: 1.0)
  pom.xml
  vaadin-portlet-integration-tests/shared/src/main/java/com/vaadin/flow/portal/AbstractPlutoPortalTest.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/lifecycle/EventHandlerIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/MinimizedStateRenderIT.java
  vaadin-portlet-integration-tests/tests-generic/src/test/java/com/vaadin/flow/portal/rendermodes/RenderIT.java
Labels: cherry pick

#252 chore: Update LICENSE
  LICENSE
Labels: target/1.0
